# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: napari workshop template
author: napari core developers
logo: logo.ico

# Only build files in the table of contents.
only_build_toc_files: true

launch_buttons:
  notebook_interface : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "cache"

# Information about where the book exists on the web
repository:
  url: https://github.com/melissawm/intro-to-napari-workshop # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
